[mypy]
python_version = 3.12
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
disable_error_code = import-untyped

# Third-party libraries without type stubs
[mypy-imapclient]
ignore_missing_imports = True

[mypy-imapclient.exceptions]
ignore_missing_imports = True

[mypy-exchangelib]
ignore_missing_imports = True
